### ISSUE TITLE
Problems with watershedding (deprecated version)

### ISSUE THREAD

**Issue by kapoorlab** [imglib/imglib2-algorithm#24] opened 2016-05-09 17:20 UTC
Hey,

I tried using watershedding implementation of imglib2, my attempt is shown below. The problem here is that it does not do watershedding, I checked with the plugin in Fiji and it works fine for the same image. The problem seems to be not in the displaying of watershedded regions but in the input image set up for the watershed object.  Any ideas why my implementation does not work?

**************************************** Using watershedding implementation of Imglib2*********************
@SuppressWarnings("deprecation")
	public static void OldWatersherImage(RandomAccessibleInterval<FloatType> inputimg,
			RandomAccessibleInterval<FloatType> seedimg, int background) {

		int n = inputimg.numDimensions();
		long[] dimensions = new long[n];
		long[] positionseed = new long[n];

		for (int d = 0; d < n; ++d)
			dimensions[d] = inputimg.dimension(d);

		final NativeImgLabeling<Integer, ShortType> outputLabeling = new NativeImgLabeling<Integer, ShortType>(
				new ArrayImgFactory<ShortType>().create(inputimg, new ShortType()));

		final NativeImgLabeling<Integer, ShortType> seedLabeling = new NativeImgLabeling<Integer, ShortType>(
				new ArrayImgFactory<ShortType>().create(seedimg, new ShortType()));

		final Cursor<LabelingType<Integer>> seedlabelcursor = seedLabeling.localizingCursor();

		ImageJFunctions.show(inputimg).setTitle("Input image for watershedding");
		ImageJFunctions.show(seedimg).setTitle("Seed image for watershedding");

		final RandomAccess<FloatType> seedcursor = seedimg.randomAccess();

		// Fill the seedlabel image

		while (seedlabelcursor.hasNext()) {
			LabelingType<Integer> seedl = seedlabelcursor.next();
			seedlabelcursor.localize(positionseed);
			seedcursor.setPosition(positionseed);
			int seedLabel = (int) seedcursor.get().get();
			if (seedLabel == background)
				continue;
			seedl.setLabel(seedLabel);

		}

		final Watershed<FloatType, Integer> watershed = new Watershed<FloatType, Integer>();
		watershed.process();

		watershed.setSeeds(seedLabeling);
		watershed.setIntensityImage(inputimg);
		watershed.setStructuringElement(AllConnectedComponents.getStructuringElement(2));
		watershed.setOutputLabeling(outputLabeling);
		watershed.getResult();
		RandomAccessibleInterval<FloatType> outimg = new ArrayImgFactory<FloatType>().create(inputimg, new FloatType());
		Cursor<LabelingType<Integer>> labelCursor = outputLabeling.cursor();
		RandomAccess<FloatType> imageRA = outimg.randomAccess();
                
		// Go through the whole image again and again for every single label,
		// until no more label is found.
		( To display the watershedded regions)
                int currentLabel = 0;
		boolean anythingFound = true;
		while (anythingFound) {
			anythingFound = false;
			labelCursor.reset();

			// Go through the whole image and add every pixel, that belongs to
			// the currently processed label
			int count = 0;
			while (labelCursor.hasNext()) {
				labelCursor.fwd();
				imageRA.setPosition(labelCursor);

				int i = (int) (imageRA.get().get());
				if (i == currentLabel) {
					anythingFound = true;
					count++;
				}
			}
			System.out.println("Number of input pixels in label " + currentLabel + ": " + count);
			currentLabel++;
			ImageJFunctions.show(outimg).setTitle("Watershed Images");
		}

**Comment by tpietzsch** [comment] 2016-05-09 17:39
Can you post a self-contained example somewhere, including the images?

**Comment by kapoorlab** [comment] 2016-05-09 20:24
Hi tpietzsch,

I have put up all the methods and the image needed in one class here: 
https://github.com/PreibischLab/ImgLib2TestEnvironment/tree/master/src/main/java/varun 
The class of interest is watershedding.java on this page.

The image used is in src/main/resources/. To prep the image for watershedding, distance transform in performed and then intensity inverted DT-image is used to calculate local maxima to get the seed image for the watershedding part, the watershedding method is the first method in the class. I have cherry picked all the methods needed for the watershedding part so the program looks like a JUnit test but for a self contained example I thought it would help identify the error in my implementation (in the method OldWatersherImage there). 

Hope this helps. Thanks.

**Comment by tpietzsch** [comment] 2016-05-10 11:14
You should set the Watershed parameters before you call `process()`
https://github.com/PreibischLab/ImgLib2TestEnvironment/blob/master/src/main/java/varun/Watershedding.java#L79-L84

You should label each seeds differently. In your case you label them all `1`. Therefore the whole image ends up labeled as `1`, as you can verify using
```
ImageJFunctions.show( outputLabeling.getStorageImg() ).setTitle( "labeling storage image" );
```

Your code for extracting the "Watershed Images" doesn't work, because
https://github.com/PreibischLab/ImgLib2TestEnvironment/blob/master/src/main/java/varun/Watershedding.java#L105
you are not reading the labeling image but the (empty) output image.

I'm closing this issue. The problem is clearly with your code, not with the imglib2 watershed implementation.

**Closed by tpietzsch** 2016-05-10 11:14 UTC
